const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("goodAgent", {
  test: "hello",
  version: process.versions.electron,
  respondPermission: (id, allow) => ipcRenderer.invoke("permission:respond", { id, allow }),
  onPermissionRequest: (cb) => ipcRenderer.on("permission:request", (_event, d) => cb(d)),
  submitQuery: (prompt, apiKey, apiUrl, model, apiFormat, files, enabledSkills, reasoning, agentName) => ipcRenderer.invoke("query:submit", { prompt, apiKey, apiUrl, model, apiFormat, files, enabledSkills, reasoning, agentName }),
  abortQuery: () => ipcRenderer.invoke("query:abort"),
  resetSession: () => ipcRenderer.invoke("session:reset"),
  listSessions: () => ipcRenderer.invoke("session:list"),
  loadSession: (id) => ipcRenderer.invoke("session:load", id),
  deleteSession: (id) => ipcRenderer.invoke("session:delete", id),
  deleteMessage: (messageId) => ipcRenderer.invoke("session:delete-message", messageId),
  searchSessions: (query, limit) => ipcRenderer.invoke("session:search", query, limit),
  getLastSession: (limit) => ipcRenderer.invoke("session:last", limit),
  getSessionStatus: () => ipcRenderer.invoke("session:status"),
  // Memory Store
  memoryReadUser: () => ipcRenderer.invoke("memory:read-user"),
  memoryWriteUser: (content) => ipcRenderer.invoke("memory:write-user", content),
  memoryReadProject: () => ipcRenderer.invoke("memory:read-project"),
  memoryWriteProject: (content) => ipcRenderer.invoke("memory:write-project", content),
  memorySearch: (query) => ipcRenderer.invoke("memory:search", query),
  // Skills
  skillsListAll: () => ipcRenderer.invoke("skills:list-all"),
  skillsLoadOne: (name) => ipcRenderer.invoke("skills:load-one", name),
  skillsSetStatus: (name, status) => ipcRenderer.invoke("skills:set-status", name, status),
  skillsDelete: (name) => ipcRenderer.invoke("skills:delete", name),
  skillsDetectPatterns: () => ipcRenderer.invoke("skills:detect-patterns"),
  skillsCuratorRun: () => ipcRenderer.invoke("skills:curator-run"),
  skillsCuratorStatus: () => ipcRenderer.invoke("skills:curator-status"),
  skillsHealth: (name) => ipcRenderer.invoke("skills:health", name),
  skillsSaveSkill: (name, meta, body) => ipcRenderer.invoke("skills:save", name, meta, body),
  listSkills: () => ipcRenderer.invoke("skills:list"),
  loadSkill: (name) => ipcRenderer.invoke("skills:load", name),
  onStreamStart: (cb) => ipcRenderer.on("stream:start", () => cb()),
  onStreamChunk: (cb) => ipcRenderer.on("stream:chunk", (_event, d) => cb(d)),
  onStreamReasoning: (cb) => ipcRenderer.on("stream:reasoning", (_event, d) => cb(d)),
  onStreamDone: (cb) => ipcRenderer.on("stream:done", () => cb()),
  onStreamError: (cb) => ipcRenderer.on("stream:error", (_event, d) => cb(d)),
  onToolStart: (cb) => ipcRenderer.on("tool:start", (_event, d) => cb(d)),
  onToolResult: (cb) => ipcRenderer.on("tool:result", (_event, d) => cb(d)),
  onSessionUpdate: (cb) => ipcRenderer.on("session:update", (_event, d) => cb(d)),
  // System prompt profiles
  listPromptProfiles: () => ipcRenderer.invoke("prompt:list"),
  savePromptProfile: (profile) => ipcRenderer.invoke("prompt:save", profile),
  deletePromptProfile: (profileId) => ipcRenderer.invoke("prompt:delete", profileId),
  activatePromptProfile: (profileId) => ipcRenderer.invoke("prompt:activate", profileId),
  // MCP
  mcpList: () => ipcRenderer.invoke("mcp:list"),
  mcpConfig: () => ipcRenderer.invoke("mcp:config"),
  mcpAdd: (name, config) => ipcRenderer.invoke("mcp:add", { name, config }),
  mcpRemove: (name) => ipcRenderer.invoke("mcp:remove", name),
  mcpRestart: (name) => ipcRenderer.invoke("mcp:restart", name),
  mcpDetectLocal: () => ipcRenderer.invoke("mcp:detect-local"),
  mcpAddRemote: (name, url, headers) => ipcRenderer.invoke("mcp:add-remote", { name, url, headers }),
  mcpSaveAll: () => ipcRenderer.invoke("mcp:save-all"),
  mcpQuickAddSearxng: (url) => ipcRenderer.invoke("mcp:quick-add-searxng", url),
  downloadMarkdown: (content) => ipcRenderer.invoke("dialog:download-markdown", content),
  // WeChat iLink Bridge
  wechatGetQrcode: () => ipcRenderer.invoke("wechat:get-qrcode"),
  wechatPollStatus: (qrcodeId) => ipcRenderer.invoke("wechat:poll-status", qrcodeId),
  wechatLogin: (creds) => ipcRenderer.invoke("wechat:login", creds),
  wechatLogout: () => ipcRenderer.invoke("wechat:logout"),
  wechatGetStatus: () => ipcRenderer.invoke("wechat:get-status"),
  onWechatBotStatus: (cb) => ipcRenderer.on("wechat:bot-status", (_e, d) => cb(d)),
  onWechatIncoming: (cb) => ipcRenderer.on("wechat:incoming", (_e, d) => cb(d)),
  syncApiToWechat: (cfg) => ipcRenderer.invoke("api:sync-to-wechat", cfg),
});
