const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("goodAgent", {
  test: "hello",
  version: process.versions.electron,
  respondPermission: (id, allow) => ipcRenderer.invoke("permission:respond", { id, allow }),
  onPermissionRequest: (cb) => ipcRenderer.on("permission:request", (_event, d) => cb(d)),
  submitQuery: (prompt, apiKey, apiUrl, model, apiFormat, files, enabledSkills, reasoning, agentName, kbEnabled, planMode, webSearchEnabled) => ipcRenderer.invoke("query:submit", { prompt, apiKey, apiUrl, model, apiFormat, files, enabledSkills, reasoning, agentName, kbEnabled, planMode, webSearchEnabled }),
  setPlanMode: (enabled) => ipcRenderer.invoke("plan-mode:set", enabled),
  getPlanMode: () => ipcRenderer.invoke("plan-mode:get"),
  abortQuery: () => ipcRenderer.invoke("query:abort"),
  resetSession: () => ipcRenderer.invoke("session:reset"),
  listSessions: () => ipcRenderer.invoke("session:list"),
  loadSession: (id, opts) => ipcRenderer.invoke("session:load", id, opts),
  deleteSession: (id) => ipcRenderer.invoke("session:delete", id),
  deleteAllSessions: () => ipcRenderer.invoke("session:delete-all"),
  deleteMessage: (messageId) => ipcRenderer.invoke("session:delete-message", messageId),
  searchSessions: (query, limit) => ipcRenderer.invoke("session:search", query, limit),
  getLastSession: (limit) => ipcRenderer.invoke("session:last", limit),
  getSessionStatus: () => ipcRenderer.invoke("session:status"),
  // Memory Store
  memoryReadUser: () => ipcRenderer.invoke("memory:read-user"),
  memoryWriteUser: (content) => ipcRenderer.invoke("memory:write-user", content),
  memoryAppendUser: (content) => ipcRenderer.invoke("memory:append-user", content),
  memoryReadProject: () => ipcRenderer.invoke("memory:read-project"),
  memoryWriteProject: (content) => ipcRenderer.invoke("memory:write-project", content),
  memoryAppendProject: (content) => ipcRenderer.invoke("memory:append-project", content),
  memorySearch: (query) => ipcRenderer.invoke("memory:search", query),
  editMessage: (messageId, newContent) => ipcRenderer.invoke("session:edit-message", messageId, newContent),
  exportSessionMarkdown: (id) => ipcRenderer.invoke("session:export-markdown", id),
  // Skills
  skillsListAll: () => ipcRenderer.invoke("skills:list-all"),
  skillsLoadOne: (name) => ipcRenderer.invoke("skills:load-one", name),
  skillsSetStatus: (name, status) => ipcRenderer.invoke("skills:set-status", name, status),
  skillsDelete: (name) => ipcRenderer.invoke("skills:delete", name),
  skillsDetectPatterns: () => ipcRenderer.invoke("skills:detect-patterns"),
  skillsCuratorRun: () => ipcRenderer.invoke("skills:curator-run"),
  skillsCuratorStatus: () => ipcRenderer.invoke("skills:curator-status"),
  skillsCuratorConfig: (config) => ipcRenderer.invoke("skills:curator-config", config),
  skillsHealth: (name) => ipcRenderer.invoke("skills:health", name),
  skillsSaveSkill: (name, meta, body) => ipcRenderer.invoke("skills:save", name, meta, body),
  skillsSearch: (query, limit) => ipcRenderer.invoke("skills:search", query, limit),
  skillsReindex: () => ipcRenderer.invoke("skills:reindex"),
  listSkills: () => ipcRenderer.invoke("skills:list"),
  loadSkill: (name) => ipcRenderer.invoke("skills:load", name),
  onStreamStart: (cb) => ipcRenderer.on("stream:start", () => cb()),
  onStreamMetrics: (cb) => ipcRenderer.on("stream:metrics", (_event, d) => cb(d)),
  onStreamChunk: (cb) => ipcRenderer.on("stream:chunk", (_event, d) => cb(d)),
  onStreamReasoning: (cb) => ipcRenderer.on("stream:reasoning", (_event, d) => cb(d)),
  onStreamDone: (cb) => ipcRenderer.on("stream:done", () => cb()),
  onStreamError: (cb) => ipcRenderer.on("stream:error", (_event, d) => cb(d)),
  onToolStart: (cb) => ipcRenderer.on("tool:start", (_event, d) => cb(d)),
  onToolResult: (cb) => ipcRenderer.on("tool:result", (_event, d) => cb(d)),
  onSubagentStart: (cb) => ipcRenderer.on("subagent:start", (_event, d) => cb(d)),
  onSubagentChunk: (cb) => ipcRenderer.on("subagent:chunk", (_event, d) => cb(d)),
  onSubagentProgress: (cb) => ipcRenderer.on("subagent:progress", (_event, d) => cb(d)),
  onSubagentDone: (cb) => ipcRenderer.on("subagent:done", (_event, d) => cb(d)),
  onSessionUpdate: (cb) => ipcRenderer.on("session:update", (_event, d) => cb(d)),
  onL0Budget: (cb) => ipcRenderer.on("l0:budget", (_event, d) => cb(d)),
  onContextUsage: (cb) => ipcRenderer.on("context:usage", (_event, d) => cb(d)),
  onTaskClear: (cb) => ipcRenderer.on("task:clear", () => cb()),
  // System prompt profiles
  listPromptProfiles: () => ipcRenderer.invoke("prompt:list"),
  getDefaultPrompt: () => ipcRenderer.invoke("prompt:default"),
  savePromptProfile: (profile) => ipcRenderer.invoke("prompt:save", profile),
  deletePromptProfile: (profileId) => ipcRenderer.invoke("prompt:delete", profileId),
  activatePromptProfile: (profileId) => ipcRenderer.invoke("prompt:activate", profileId),
  // MCP
  mcpList: () => ipcRenderer.invoke("mcp:list"),
  mcpConfig: () => ipcRenderer.invoke("mcp:config"),
  mcpAdd: (name, config) => ipcRenderer.invoke("mcp:add", { name, config }),
  mcpRemove: (name) => ipcRenderer.invoke("mcp:remove", name),
  mcpRestart: (name) => ipcRenderer.invoke("mcp:restart", name),
  mcpDetectLocal: () => ipcRenderer.invoke("mcp:detect-local"),
  mcpAddRemote: (name, url, headers) => ipcRenderer.invoke("mcp:add-remote", { name, url, headers }),
  mcpSaveAll: () => ipcRenderer.invoke("mcp:save-all"),
  mcpQuickAddSearxng: (url) => ipcRenderer.invoke("mcp:quick-add-searxng", url),
  downloadMarkdown: (content) => ipcRenderer.invoke("dialog:download-markdown", content),
  // WeChat iLink Bridge
  wechatGetQrcode: () => ipcRenderer.invoke("wechat:get-qrcode"),
  wechatPollStatus: (qrcodeId) => ipcRenderer.invoke("wechat:poll-status", qrcodeId),
  wechatLogin: (creds) => ipcRenderer.invoke("wechat:login", creds),
  wechatLogout: () => ipcRenderer.invoke("wechat:logout"),
  wechatGetStatus: () => ipcRenderer.invoke("wechat:get-status"),
  onWechatBotStatus: (cb) => ipcRenderer.on("wechat:bot-status", (_e, d) => cb(d)),
  onWechatIncoming: (cb) => ipcRenderer.on("wechat:incoming", (_e, d) => cb(d)),
  syncApiToWechat: (cfg) => ipcRenderer.invoke("api:sync-to-wechat", cfg),
  // AskUserQuestion
  onAskQuestion: (cb) => ipcRenderer.on("ask:question", (_e, d) => cb(d)),
  respondQuestion: (id, answers) => ipcRenderer.invoke("ask:respond", { id, answers }),
  // Memory (multi-file)
  memoryListAll: () => ipcRenderer.invoke("memory:list-all"),
  memoryReadOne: (filename) => ipcRenderer.invoke("memory:read-one", filename),
  memoryCreate: (name, description, type, content) => ipcRenderer.invoke("memory:create", { name, description, type, content }),
  memoryUpdate: (filename, content, name, description, type) => ipcRenderer.invoke("memory:update", { filename, content, name, description, type }),
  memoryDelete: (filename) => ipcRenderer.invoke("memory:delete", filename),
  workspaceGet: () => ipcRenderer.invoke("workspace:get"),
  workspaceSet: (path) => ipcRenderer.invoke("workspace:set", path),
  workspacePick: () => ipcRenderer.invoke("workspace:pick"),
  workspaceNeedsFirstPick: () => ipcRenderer.invoke("workspace:needs-first-pick"),
  // Knowledge Base
  kbGetVault: () => ipcRenderer.invoke("kb:get-vault"),
  kbSetVault: (path) => ipcRenderer.invoke("kb:set-vault", path),
  kbPickVault: () => ipcRenderer.invoke("kb:pick-vault"),
  kbConfig: () => ipcRenderer.invoke("kb:config"),
  kbSetConfig: (cfg) => ipcRenderer.invoke("kb:set-config", cfg),
  kbScan: () => ipcRenderer.invoke("kb:scan"),
  kbStatus: () => ipcRenderer.invoke("kb:status"),
  kbSearch: (query, limit) => ipcRenderer.invoke("kb:search", query, limit),
  kbList: (offset, limit) => ipcRenderer.invoke("kb:list", offset, limit),
  kbGetNote: (path) => ipcRenderer.invoke("kb:get-note", path),
  kbCreateNote: (path, content, tags) => ipcRenderer.invoke("kb:create-note", { path, content, tags }),
  kbUpdateNote: (path, content) => ipcRenderer.invoke("kb:update-note", { path, content }),
  kbDeleteNote: (path) => ipcRenderer.invoke("kb:delete-note", path),
  kbOllamaModels: () => ipcRenderer.invoke("kb:ollama-models"),

  // Update Manager
  updateCheckVersion: () => ipcRenderer.invoke("update:get-version"),
  updateCheckForUpdates: () => ipcRenderer.invoke("update:check"),
  updateInstall: () => ipcRenderer.invoke("update:install"),
  onUpdateStatus: (cb) => ipcRenderer.on("update:status", (_e, d) => cb(d)),
  onUpdateProgress: (cb) => ipcRenderer.on("update:progress", (_e, d) => cb(d)),

  // Encrypted API Key Storage
  saveApiKey: (provider, key) => ipcRenderer.invoke("api-key:save", { provider, key }),
  loadApiKey: (provider) => ipcRenderer.invoke("api-key:load", { provider }),
  deleteApiKey: (provider) => ipcRenderer.invoke("api-key:delete", { provider }),
  getEnvVar: (name) => ipcRenderer.invoke("env:get", name),
});
